# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ru-RU"
reviews:
  profile: "assertive" # Строгий режим (находит мелкие недочеты)
  path_instructions:
    - path: "**/[^_]*[!_test].go" 
      instructions: |
        - Следи за обработкой ошибок: ошибка не должна игнорироваться (`_`), всегда проверяй `if err != nil`.
        - Проверяй использование `context.Context`: он должен быть первым аргументом функций и не храниться в структурах.
        - Ищи потенциальные утечки горутин: убедись, что каналы закрываются, а контексты отменяются.
        - Для публичных методов требуй комментарии в стиле Go (начинающиеся с имени функции).
        - Следи за конкурентностью: использование mutex должно сопровождаться `defer m.Unlock()`.
    - path: "**/*_test.go"
      instructions: |
        - Здесь игнорирование ошибок через `_` допустимо, если это не влияет на результат теста.
        - Следи, чтобы тесты были атомарными и не зависели от порядка запуска.
        - При использовании `testify`, отдавай предпочтение `require` вместо `assert` для критичных проверок.
        - Проверяй, что `t.Parallel()` используется там, где это безопасно.
    - path: "**/internal/**"
      instructions: "Убедись, что логика здесь не импортируется внешними пакетами, соблюдая инкапсуляцию."